apiVersion: v1
kind: Service
metadata:
  name: aiops-sample-app
  namespace: aiops
  labels:
    app: aiops-sample-app
spec:
  type: ClusterIP
  selector:
    app: aiops-sample-app
  ports:
    - name: http
      port: 80
      targetPort: http
