apiVersion: v1
kind: Service
metadata:
  name: aiops-ai-agent
  namespace: aiops
  labels:
    app: aiops-ai-agent
spec:
  type: ClusterIP
  selector:
    app: aiops-ai-agent
  ports:
    - name: http
      port: 80
      targetPort: http
